/*jshint node:true, esversion:6, maxlen: 120 */

'use strict';
// jquery-like api for navigating the dom of html generated by the templating engine
const dom = require("cheerio");
const escapeHtml = require("escape-html");
const promisify = require("es6-promisify");
const readFile = promisify(require('fs').readFile);
const path = require("path");
const stream = require("stream");

const talisman = require("../lib/talisman");

// Read the template file
const htmlPromise = readFile(path.join(__dirname, "testTemplate.html"), 'utf8');
// read a file full of random strings
const randomPromise = readFile(path.join(__dirname, "random.html"), 'utf8');

process.on('unhandledRejection', function (err) {
    console.log('Unhandled Rejection: ' + err.stack || err);
});

function templateTest (test) {
    const templateFile = path.join(__dirname, "testTemplate.html");
    const template = talisman.template(templateFile);
    template.render();
    test.done();
}

module.exports = {
    templateTest
};
